config/routes.rb
Imobilius::Application.routes.draw do
  devise_for :users

  resources :properties do
    get :pictures_upload
  end

  resources :pictures, :only => [:index, :create, :destroy]

  

end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :districts
  belongs_to :state

end

app/models/district.rb
class District < ActiveRecord::Base

  belongs_to :city

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  image_accessor :file

  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :property

  #attr_accessible :file_uid, :file_name, :file
   #one convenient method to pass jq_upload the necessary information
   
  def to_jq_upload
    {
      "name" => read_attribute(:file_name),
      "size" => file.size,
      "url" => file.url,
      "thumbnail_url" => file.thumb('80x80#').url,
      "delete_url" => picture_path(:id => id),
      "delete_type" => "DELETE" 
    }
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  has_many :pictures
  belongs_to :district

  def get_cover
  	cover = pictures.where(property_id: id, cover: true).first
    if cover
      return cover
    end
    false
  end

end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :cities

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    #@pictures = Picture.all
    #render :json => @pictures.collect { |p| p.to_jq_upload }.to_json
    render :json => [].to_json
  end

  def create
    @picture = Picture.new params.require(:picture).permit(:file, :file_uid, :file_name, :property_id)
    #@task = Task.new(:parent_id => params[:parent_id], :project_id => params[:project_id])

    if @picture.save
      respond_to do |format|
        format.html {  
          render :json => [@picture.to_jq_upload].to_json, 
          :content_type => 'text/html',
          :layout => false
        }
        format.json {  
          #render :json => [@picture.to_jq_upload].to_json 
          render json: {files: [@picture.to_jq_upload]}, status: :created, location: @picture    
        }
      end
    else 
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    render :json => true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @property = Property.new

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.json { render json: @property }
    end
  end

  def create
    @property = Property.new params.require(:property).permit(:description, :value)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @property = Property.find(params[:id])
    render :layout => !request.xhr?
  end

  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def pictures_upload
    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.json { render json: @property }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imobilius</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>  
</head>
<body>


  <div id="header">
    <h1><a href="./dashboard.html">Unicorn Admin</a></h1>   
  </div>

<!--   <div id="search">
    <input type="text" placeholder="Search here..."/><button type="submit" class="tip-right" title="Search"><i class="icon-search icon-white"></i></button>
  </div> -->
  <div id="user-nav" class="navbar navbar-inverse">
    <ul class="nav btn-group">
      <li class="btn btn-inverse" ><a title="" href="#"><i class="icon icon-user"></i> <span class="text">Profile</span></a></li>
      <li class="btn btn-inverse dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a class="sAdd" title="" href="#">new message</a></li>
          <li><a class="sInbox" title="" href="#">inbox</a></li>
          <li><a class="sOutbox" title="" href="#">outbox</a></li>
          <li><a class="sTrash" title="" href="#">trash</a></li>
        </ul>
      </li>
      <li class="btn btn-inverse"><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
      <li class="btn btn-inverse"><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
    </ul>
  </div>

  <div id="sidebar">
    <a href="#" class="visible-phone"><i class="fa-icon fa-icon-home"></i> Imóveis</a>
    <ul>
            <li class="submenu">
        <a href="#"><i class="fa-icon fa-icon-smile"></i> <span>Clientes</span> <span class="label">3</span></a>
        <ul>
          <li class="active"><a href="form-common.html">Listar Todos</a></li>
          <li><a href="form-validation.html">Cadastrar Novo</a></li>
          <li><a href="form-wizard.html">Relatórios</a></li>
        </ul>
      </li>
      <li class="submenu">
        <a href="#"><i class="fa-icon fa-icon-group"></i> <span>Corretores</span> <span class="label">3</span></a>
        <ul>
          <li class="active"><a href="form-common.html">Listar Todos</a></li>
          <li><a href="form-validation.html">Cadastrar Novo</a></li>
          <li><a href="form-wizard.html">Relatórios</a></li>
        </ul>
      </li>
      <li class="submenu active open">
        <a href="#"><i class="fa-icon fa-icon-home"></i> <span>Imóveis</span> <span class="label">3</span></a>
        <ul>
          <li class="active"><a href="form-common.html">Listar Todos</a></li>
          <li><a href="form-validation.html">Cadastrar Novo</a></li>
          <li><a href="form-wizard.html">Relatórios</a></li>
        </ul>
      </li>
      <li class="submenu">
        <a href="#"><i class="fa-icon fa-icon-list-alt"></i> <span>Relatórios</span> <span class="label">3</span></a>
        <ul>
          <li><a href="form-common.html">Clientes</a></li>
          <li><a href="form-validation.html">Imóveis</a></li>
          <li><a href="form-wizard.html">Corretores</a></li>
        </ul>
      </li>
      <li class="submenu">
        <a href="#"><i class="fa-icon fa-icon-globe"></i> <span>Website</span> <span class="label">3</span></a>
        <ul>
          <li><a href="form-common.html">Clientes</a></li>
          <li><a href="form-validation.html">Imóveis</a></li>
          <li><a href="form-wizard.html">Corretores</a></li>
        </ul>
      </li>
      <li class="submenu">
        <a href="#"><i class="fa-icon fa-icon-tablet"></i> <span>Catálogo Móvel</span> <span class="label">3</span></a>
        <ul>
          <li><a href="form-common.html">Clientes</a></li>
          <li><a href="form-validation.html">Imóveis</a></li>
          <li><a href="form-wizard.html">Corretores</a></li>
        </ul>
      </li>
    </ul>

  </div>

  <div id="content">
    <%= yield %>
    
            </div>

          </div>

        </div>  
      </div>


      <div class="row-fluid">
        <div id="footer" class="span12">
          2012 - 2013 &copy; Unicorn Admin. Brought to you by <a href="https://wrapbootstrap.com/user/diablo9983">diablo9983</a>
        </div>
      </div>
    </div>
  </div>
  


</body>
</html>

app/views/properties/_form.html.erb
<%= simple_form_for @property, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="widget-box">
              <div class="widget-title">
                <span class="icon">
                  <i class="icon-align-justify"></i>                  
                </span>
                <h5>Endereço</h5>
              </div>
              <div class="widget-content nopadding">
  <div class="control-group form-inline">
    <%= f.label :address_name %>
    <div class="controls">
      <%= f.text_field :address_name %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :address_number %>
    <div class="controls">
      <%= f.text_field :address_number %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_complement %>
    <div class="controls">
      <%= f.text_field :address_complement %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_reference %>
    <div class="controls">
      <%= f.text_field :address_reference %>
    </div>
  </div>
  <div class="control-group">
      <%= f.association :district %>
  </div>
  
  </div>  
</div>

<div class="widget-box">
<div class="widget-title">
  <span class="icon">
    <i class="icon-align-justify"></i>                  
  </span>
  <h5>Medidas</h5>
</div>
<div class="widget-content nopadding">

  <div class="control-group">
    <%= f.label :privative_area %>
    <div class="controls">
      <%= f.text_field :privative_area %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :constructed_area %>
    <div class="controls">
      <%= f.text_field :constructed_area %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :total_area %>
    <div class="controls">
      <%= f.text_field :total_area %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :terrain_area %>
    <div class="controls">
      <%= f.text_field :terrain_area %>
    </div>
  </div>

   </div>  
</div>

<div class="widget-box">
<div class="widget-title">
  <span class="icon">
    <i class="icon-align-justify"></i>                  
  </span>
  <h5>Dados sobre o Imóvel</h5>
</div>
<div class="widget-content nopadding">

  <div class="control-group">
    <%= f.label :bedrooms %>
    <div class="controls">
      <%= f.text_field :bedrooms %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :suits %>
    <div class="controls">
      <%= f.text_field :suits %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :construction_year %>
    <div class="controls">
      <%= f.text_field :construction_year %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :garages %>
    <div class="controls">
      <%= f.text_field :garages %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :furnished %>
    <div class="controls">
      <%= f.text_field :furnished %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description %>
    <div class="controls">
      <%= f.text_field :description %>
    </div>
  </div>
   </div>  
</div>

<div class="widget-box">
<div class="widget-title">
  <span class="icon">
    <i class="icon-align-justify"></i>                  
  </span>
  <h5>Dados Comerciais</h5>
</div>
<div class="widget-content nopadding">

  <div class="control-group">
    <%= f.label :sell_price %>
    <div class="controls">
      <%= f.text_field :sell_price %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :client_price %>
    <div class="controls">
      <%= f.text_field :client_price %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :value %>
    <div class="controls">
      <%= f.text_field :value %>
    </div>
  </div>
   </div>  
</div>

  <div class="actions">
    <%= f.submit %>
  </div>

 
<% end %>
<!--
    t.integer  "privative_area"
    t.integer  "constructed_area"
    t.integer  "total_area"
    t.integer  "terrain_area"
    t.integer  "sell_price"
    t.integer  "client_price"
    t.integer  "bedrooms"
    t.integer  "bathrooms"
    t.integer  "suits"
    t.integer  "construction_year"
    t.integer  "garages"
    t.boolean  "furnished"
  -->


app/views/properties/_pictures_upload.html.erb
<h2>Titulo <%= @property.id %></h2>
    <%= form_for Picture.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
        <%= f.hidden_field :property_id, value: @property.id %>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add files...</span>
                    <%= f.file_field :file, :multiple => true %>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    <% end %>

<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>





<script type="text/javascript" charset="utf-8">
    $(function () {
        // Initialize the jQuery File Upload widget:
        //$('#fileupload').fileupload();
        $('#fileupload').fileupload({
            paramName: 'picture[file]'
        });
        // 
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimp-fileupload'), 
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));

        // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
</script>

app/views/properties/edit.html.erb
<div id="content-header">
  <h1>Editar Imóvel - Cód. <%= @property.id %></h1>

  <div class="btn-group">
    <a class="btn btn-large tip-bottom" title="Manage Files"><i class="icon-file"></i></a>
    <a class="btn btn-large tip-bottom" title="Manage Users"><i class="icon-user"></i></a>
    <a class="btn btn-large tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a>
    <a class="btn btn-large tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a>
  </div>
</div>
<div id="breadcrumb">
  <a href="index.html" title="" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Imóveis</a>
  <a href="#">Editar</a>
  <a href="#" class="current">Cód. <%= @property.id %></a>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12 center" style="text-align: center;">         

      <div class="widget-box">
        <div class="widget-title">
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Cadastro</a></li>
            <li><a data-toggle="tab" href="#tab2"><i class="fa-icon-picture"></i> Fotos</a></li>
            <li><a data-toggle="tab" href="#tab3"><i class="fa-fa-icon-globe"></i> Website</a></li>
            <li><a data-toggle="tab" href="#tab3"><i class="fa-fa-icon-tablet"></i> Catálogo Móvel</a></li>
          </ul>
        </div>
        <div class="widget-content tab-content">
          <div id="tab1" class="tab-pane active">
            <%= render 'form' %>
          </div>
          <div id="tab2" class="tab-pane">

            <div class="btn-toolbar">
              <div class="btn-group" data-toggle="buttons-radio">
                <button class="btn" onClick='javascript:return resort_images();' data-original-title="Bold - Ctrl+B">
                  <i class="fa-icon-move"></i>
                  Ordenar
                </button>
                <button class="btn" onClick='javascript:return select_cover();' data-original-title="Italic - Ctrl+I">
                  <i class="fa-icon-picture"></i>
                  Selecionar capa
                </button>
                <button class="btn" onClick='javascript:return select_website_images();' data-original-title="Italic - Ctrl+I">
                  <i class="fa-icon-globe"></i>
                  Website
                </button>
                <button class="btn" onClick='javascript:return select_mobile_images();' data-original-title="Italic - Ctrl+I">
                  <i class="fa-icon-tablet"></i>
                  Catálogo Móvel
                </button>
              </div>
              
              <a href="#static" data-url="<%= property_pictures_upload_path(:property_id => @property.id)%>" data-toggle="modal" class="pictures-upload-button btn btn-success"><i class="fa-icon-upload-alt"></i> Adicionar</a>  

              <button class="btn btn-danger" onClick='javascript:return select_delete();' data-original-title="Bold - Ctrl+B">
                <i class="fa-icon-remove"></i> 
                Excluir
              </button>
              <button class="btn btn-primary" onClick='javascript:return deactivate_all();' data-original-title="Bold - Ctrl+B">
                <i class="icon-ok icon-white"></i> 
                Salvar alterações
              </button>

            </div>

            <ul id="sortable">
              
              <% @property.pictures.each do |picture| %>
                <li class="ui-state-default wrapper span3">
                  <a title="Terras vizinhas" class="fancybox" href="<%= picture.file.url %>">
                    <img src="<%= picture.file.thumb('288x216#').url %>" alt=""/>
                  </a>
                  <div class="published">
                    <i class="fa-icon-globe" data-toggle="tooltip" title="Disponivel no website" style="display: none;"></i>
                    <i class="fa-icon-tablet" data-toggle="tooltip" title="Não está disponivel no catálogo móvel" style="display: none;"></i>       

                  </div>

                  <div class="delete-picture">
                    <i class="fa-icon-remove" data-toggle="tooltip" title="Disponivel no website" style="display: none;"></i>
                  </div>
                </li>
                
              <% end %>

            </ul>

          </div>
          <div id="tab3" class="tab-pane">This is a Tab Three Content

          </div>
        </div>                            
      </div>
    </div>




  </div>
  <!-- </div> -->

</div>

<script>
(function() {
  $('.pictures-upload-button').click(function() {
    var url;

    url = $(this).data('url');
    return $.ajax({
      url: url,
      type: "GET",
      success: function(data) {
        return $('#static .modal-body').html(data);
      },
      error: function() {
        return $('#static .modal-body').html("ERROR");
      }
    });
  });

}).call(this);

$.fn.modal.defaults.height = function(){
    // subtract the height of the modal header and footer
    return $(window).height() - 265; 
}
$.fn.modal.defaults.width = 750;
</script>

<div id="static" class="modal hide fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
  <div class="modal-header">    
    <button type="button" data-dismiss="modal" class="btn close-modal">Fechar</button>
    <h2>Adicionar novas fotografias</h2>
  </div>
  <div class="modal-body">
    <p>Carregando...</p>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn">Fechar</button>
  </div>
</div>

app/views/properties/index.html.erb
<div id="content-header">
  <h1>Lista de imóveis</h1>

  <div class="btn-group">
    <a class="btn btn-large tip-bottom" title="Manage Files"><i class="icon-file"></i></a>
    <a class="btn btn-large tip-bottom" title="Manage Users"><i class="icon-user"></i></a>
    <a class="btn btn-large tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a>
    <a class="btn btn-large tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a>
  </div>
</div>
<div id="breadcrumb">
  <a href="index.html" title="" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Imóveis</a>
  <a href="#" class="current">Listar</a>
</div>
<div class="container-fluid">
  <div class="row-fluid">

    <div id="tools">
      <a href="#" class="btn"><i class="fa-icon-folder-open"></i> Archive</a>

      <a href="#" class="btn btn-success pull-right spaced"><i class="fa-icon-plus fa-icon-white"></i> Novo Imóvel</a>

      <div class="btn-group pull-right spaced" >
        <button class="btn span2">Sort By</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </div>

      <div class="input-append pull-right spaced">
        <input class="span3" id="appendedInputButton" type="text" value="Filter by..."></input>
        <button class="btn" type="button">Filter!</button>
      </div>

    </div>

    <div id="properties">
      <table class="table">
        <tbody>
          <% @properties.each  do |property| %>
          <tr>
            <td>
              <i class="fa-icon-2x fa-icon-star" style="color: rgb(211, 211, 211);" data-toggle="tooltip" title="Imóvel não está em destaque"></i>
              <i class="fa-icon-2x fa-icon-globe" style="color: rgb(211, 211, 211);" data-toggle="tooltip" title="Não está disponivel no website"></i>
              <i class="fa-icon-2x fa-icon-tablet" style="color: rgb(211, 211, 211);" data-toggle="tooltip" title="Não está disponivel no catálogo móvel"></i>
            </td>
            <td>
              <% if property.get_cover %>
              <img src="<%= property.get_cover.file.thumb('130x100#').url %>" alt=""/>
              <%else %>
              <img src="/assets/no_cover.png" alt=""/>
              <% end %>
            </td>
            <td>
              <b>
                Ref: <%= property.id %>
              </b>
              <br>
              <b> Área para Venda </b>
              <br> 
              <b> Proprietário: </b>
              Jean Brito
              <br>
              <b> Localidade: </b>
              Jardim do Prado, Taquara - RS
              <br>
              <b> Valor: </b>
              <%= property.value %>
            </td>
            <td>
              <%= link_to(property,
                method: :get,
                class: 'btn btn-primary') do %>
                <%= content_tag('i', nil, class: '') %> Abrir Imóvel
                <% end %>

                <%= link_to(edit_property_path(property),
                  method: :get,
                  class: 'btn') do %>
                  <%= content_tag('i', nil, class: 'icon-edit') %> Editar
                  <% end %>              
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>